server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/virtual?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: a2288311
    xa:
      properties:
        useInformationSchema: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: src/main/resources
  freemarker:
    cache: false
  # 日志
logging:
  config: classpath:logback-spring.xml
  file:
    path: ../logs/virtual
mybatis:
  type-aliases-package: com.nov.virtual.sql.mapper
  mapper-locations: classpath:mapping/*.xml




